<?xml version="1.0"?>

<robot name="kuvshinka" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Добавление файла с подключениями различных плагинов Gazebo -->
  <xacro:include filename="kuvshinka.gazebo.xacro" />


  <!-- Числовые константы (просто упрощаем себе жизнь) -->
  <xacro:property name="base_width" value="0.46"/>
  <xacro:property name="base_length" value="0.08"/>

  <xacro:property name="wheel_radius" value="0.16"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.22"/>
  <xacro:property name="wheel_zoff" value="0.08"/>
  <xacro:property name="wheel_xoff" value="0.16"/>

  <xacro:property name="caster_xoff" value="0.30"/>
  <xacro:property name="caster_size" value="0.16"/>

  <xacro:property name="petal_size" value="0.12"/>

  <xacro:property name="test_maxwidth" value="2.10"/>
  <xacro:property name="test_maxheight" value="2.50"/>


  <!-- Здесь описываем "материалы" (из какого цвета будут детаели) -->
  <material name="greeen">
    <color rgba="0.1 0.3 0 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="pinkish">
    <color rgba="0.9 0.7 0.8 1"/>
  </material>
  <material name="yellowish">
    <color rgba="0.8 0.7 0.3 1"/>
  </material>
  <material name="red">
    <color rgba="0.6 0 0 1"/>
  </material>


  <!-- Задаём макросы xacro -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>


  <!-- Базовая фигура, к ней должно крепиться всё остальное -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_length}" radius="${base_width}"/>
      </geometry>
      <material name="greeen" />
    </visual>

    <collision>
      <geometry>
        <cylinder length="${base_length}" radius="${base_width}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="15" r="${base_width}" h="${base_length}"/>
  </link>

  <link name="base_top">
    <visual>
      <geometry>
        <cylinder length="${base_length}" radius="${base_width}"/>
      </geometry>
      <material name="greeen" />
    </visual>

    <collision>
      <geometry>
        <cylinder length="${base_length}" radius="${base_width}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="15" r="${base_width}" h="${base_length}"/>
  </link>

  <joint name="base_top_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_top"/>
    <origin xyz="0 0 ${base_length}" rpy="0 0 0"/>
  </joint>


  <!-- Колёса, задаются сразу несколько колёс через макрос -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 ${base_length/4}" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black" />
      </visual>

      <collision>
        <origin xyz="0 0 ${base_length/4}" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="wheel_left" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="wheel_right" x_reflect="-1" y_reflect="-1" />


  <!-- Сфера (уже не совсем) спереди снизу, называется кастер -->
  <link name="caster">
    <visual>
      <geometry>
        <box size="${caster_size} ${caster_size*2} ${caster_size}"/>
      </geometry>
      <material name="red" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${caster_size} ${caster_size*2} ${caster_size}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_width/4))}"/>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${caster_xoff} 0.0 ${wheel_zoff*-1.4}" rpy="0 2 0"/>
  </joint>


  <!-- Ну и просто для красоты добавим кувшинке лепестки наружние... -->
  <xacro:macro name="petal_outer" params="skew petal_no petal_total">
    <link name="petal_outer_${skew}_${petal_no}">
      <visual>
        <geometry>
          <box size="${petal_size} ${petal_size*6} ${petal_size/2}"/>
        </geometry>
        <material name="pinkish" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${petal_size} ${petal_size*6} ${petal_size/2}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.2" w="${petal_size}" h="${petal_size*6}" d="${petal_size/2}"/>
    </link>

    <joint name="petal_outer_${skew}_${petal_no}_joint" type="fixed">
      <parent link="base_top"/>
      <child link="petal_outer_${skew}_${petal_no}"/>
      <origin xyz="0 0 ${base_length}" rpy="${15.8 + skew} 6 ${(skew*2 + petal_no / petal_total) * pi*2}"/>
    </joint>
  </xacro:macro>

  <xacro:petal_outer skew="0.0" petal_no="1" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="2" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="3" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="4" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="5" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="6" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="7" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="8" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="9" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="10" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="11" petal_total="12" />
  <xacro:petal_outer skew="0.0" petal_no="12" petal_total="12" />

  <xacro:petal_outer skew="0.3" petal_no="1" petal_total="8" />
  <xacro:petal_outer skew="0.3" petal_no="2" petal_total="8" />
  <xacro:petal_outer skew="0.3" petal_no="3" petal_total="8" />
  <xacro:petal_outer skew="0.3" petal_no="4" petal_total="8" />
  <xacro:petal_outer skew="0.3" petal_no="5" petal_total="8" />
  <xacro:petal_outer skew="0.3" petal_no="6" petal_total="8" />
  <xacro:petal_outer skew="0.3" petal_no="7" petal_total="8" />
  <xacro:petal_outer skew="0.3" petal_no="8" petal_total="8" />

  <xacro:petal_outer skew="0.5" petal_no="1" petal_total="8" />
  <xacro:petal_outer skew="0.5" petal_no="2" petal_total="8" />
  <xacro:petal_outer skew="0.5" petal_no="3" petal_total="8" />
  <xacro:petal_outer skew="0.5" petal_no="4" petal_total="8" />
  <xacro:petal_outer skew="0.5" petal_no="5" petal_total="8" />
  <xacro:petal_outer skew="0.5" petal_no="6" petal_total="8" />
  <xacro:petal_outer skew="0.5" petal_no="7" petal_total="8" />
  <xacro:petal_outer skew="0.5" petal_no="8" petal_total="8" />


  <!-- ...и лепестки внутренние -->
  <xacro:macro name="petal_inner" params="petal_no petal_total">
    <link name="petal_inner_${petal_no}">
      <visual>
        <geometry>
          <box size="${petal_size/2} ${petal_size*4} ${petal_size/2}"/>
        </geometry>
        <material name="yellowish" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${petal_size/2} ${petal_size*4} ${petal_size/2}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.2" w="${petal_size/2}" h="${petal_size*4}" d="${petal_size/2}"/>
    </link>

    <joint name="petal_inner_${petal_no}_joint" type="fixed">
      <parent link="base_top"/>
      <child link="petal_inner_${petal_no}"/>
      <origin xyz="0 0 ${base_length*2}" rpy="16.8 6 ${(petal_no / petal_total) * pi*2}"/>
    </joint>
  </xacro:macro>

  <xacro:petal_inner petal_no="1" petal_total="3" />
  <xacro:petal_inner petal_no="2" petal_total="3" />
  <xacro:petal_inner petal_no="3" petal_total="3" />
</robot>
