<?xml version="1.0"?>

<robot name="NO_NAME_GIVEN_FOR_THE_ROBOT" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Импорт файла с подключениями различных плагинов Gazebo -->
  <xacro:include filename="robot.gazebo.xacro" />
  <!-- Импорт файла с настройками плагина детали лидара и описанием его внешнего вида -->
  <xacro:include filename="lidar.urdf.xacro" />
  <!-- Импорт файла с настройками плагина детали камеры цвета И глубины и описанием её внеш. вида -->
  <xacro:include filename="depth.urdf.xacro" />
  <!-- Импорт файла с настройками плагина детали инерц. гиростабилизатора и опис. его внеш. вида -->
  <xacro:include filename="imu.urdf.xacro" />


  <!-- Числовые константы (просто упрощаем себе жизнь) -->
  <xacro:property name="base_width" value="0.40"/>
  <xacro:property name="base_length" value="0.28"/>

  <xacro:property name="wheel_radius" value="0.20"/>
  <xacro:property name="wheel_width" value="0.10"/>
  <xacro:property name="wheel_ygap" value="0.20"/>
  <xacro:property name="wheel_zoff" value="0.08"/>
  <xacro:property name="wheel_xoff" value="0.14"/>

  <xacro:property name="caster_xoff" value="0.36"/>
  <xacro:property name="caster_zoff" value="0.08"/>


  <!-- Здесь описываем "материалы" (из какого цвета будут детаели) -->
  <material name="mango">
    <color rgba="0.8 0.5 0.3 1"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1"/>
  </material>


  <!-- Задаём макросы xacro -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>


  <!-- Базовая фигура, к ней должно крепиться всё остальное -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_length}" radius="${base_width}"/>
      </geometry>
      <material name="mango" />
    </visual>

    <collision>
      <geometry>
        <cylinder length="${base_length}" radius="${base_width}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="15" r="${base_width}" h="${base_length}"/>
  </link>


  <!-- Колёса, задаются сразу несколько колёс через макрос -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="white" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="wheel_left" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="wheel_right" x_reflect="-1" y_reflect="-1" />


  <!-- Сфера спереди снизу, называется кастер -->
  <link name="caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_width/4))}"/>
      </geometry>
      <material name="white" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_width/4))}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_width/4))}"/>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-caster_zoff}" rpy="0 0 0"/>
  </joint>
</robot>
