- ros_topic_name: '/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_topic_name: '/model/robot/cmd_vel'
  gz_type_name: 'gz.msgs.Twist'
  direction: ROS_TO_GZ
- ros_topic_name: '/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_topic_name: '/model/robot/odometry'
  gz_type_name: 'gz.msgs.Odometry'
  direction: GZ_TO_ROS
- ros_topic_name: '/tf'
  ros_type_name: 'tf2_msgs/msg/TFMessage'
  gz_topic_name: '/model/robot/tf'
  gz_type_name: 'gz.msgs.Pose_V'
  direction: GZ_TO_ROS
- ros_topic_name: '/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_topic_name: '/world/shapes/model/robot/joint_state'
  gz_type_name: 'gz.msgs.Model'
  direction: GZ_TO_ROS

- ros_topic_name: "/robot/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_topic_name: "/world/shapes/model/robot/link/base_link/sensor/laser_sensor_frame/scan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_topic_name: "/world/shapes/model/robot/link/base_link/sensor/depth_sensor_frame/camera_info"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_topic_name: "/world/shapes/model/robot/link/base_link/sensor/depth_sensor_frame/depth_image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_topic_name: "/world/shapes/model/robot/link/base_link/sensor/depth_sensor_frame/depth_image/points"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_topic_name: "/world/shapes/model/robot/link/base_link/sensor/color_sensor_frame/camera_info"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_topic_name: "/world/shapes/model/robot/link/base_link/sensor/color_sensor_frame/image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
