- ros_topic_name: '/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_topic_name: '/model/kuvshinka/cmd_vel'
  gz_type_name: 'gz.msgs.Twist'
  direction: ROS_TO_GZ
- ros_topic_name: '/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_topic_name: '/model/kuvshinka/odometry'
  gz_type_name: 'gz.msgs.Odometry'
  direction: GZ_TO_ROS
- ros_topic_name: '/tf'
  ros_type_name: 'tf2_msgs/msg/TFMessage'
  gz_topic_name: '/model/kuvshinka/tf'
  gz_type_name: 'gz.msgs.Pose_V'
  direction: GZ_TO_ROS
- ros_topic_name: '/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_topic_name: '/world/shapes/model/kuvshinka/joint_state'
  gz_type_name: 'gz.msgs.Model'
  direction: GZ_TO_ROS
